# Generated by Django 2.2 on 2019-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=15)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
    ]
